In [1]:
import numpy as np

## 2. Creating Arrays
- [x] np.array()
- [x] 1D Arrays
- [x] 2D Arrays
- [x] 3D Arrays
- [x] Array dimensions (ndim)
- [x] Array shape
- [x] Array datatype (dtype)

In [3]:
a = np.array([1,2,3,4])
b = np.array([
    [1,2,3,4],
    [5,6,7,8]
    ])
c = np.array([[
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
    ]])
print(a.ndim)
print(b.ndim)
print(c.ndim)

print(a.shape)
print(b.shape)
print(c.shape)

print(a.size)
print(b.size)
print(c.size)

print(a.dtype)
print(b.dtype)
print(c.dtype)

1
2
3
(4,)
(2, 4)
(1, 3, 4)
4
8
12
int64
int64
int64


## 3. Special Arrays
- [x] np.zeros()
- [x] np.ones()
- [x] np.empty()
- [x] np.full()
- [x] np.eye()
- [x] np.arange()
- [x] np.linspace()
- [x] Random arrays

In [4]:
print(np.zeros((2,3)))
print(np.ones((2,3)))
print(np.full((2,3), 5))
print(np.eye(3))
print(np.empty((2,3)))
print(np.arange(0,10,2))
print(np.linspace(0,1,5))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[2.5e-323 2.5e-323 2.5e-323]
 [2.5e-323 2.5e-323 2.5e-323]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


## 5. Indexing & Slicing
- [ ] Accessing elements
- [ ] Negative indexing
- [ ] Slicing arrays
- [ ] Multi-dimensional indexing
- [ ] Boolean indexing
- [ ] Fancy indexing

In [6]:
print(a[0])
print(b[0,1])
print(c[0,1,2])

print(a[-1])
print(b[-1,-1])
print(c[-1,-1,-1])

print(a[0:2])
print(b[:,1])
print(c[0,1,:])

mask = a>5
print(mask)

print(a[[0,2,1]])
print(a[[0,1,1]])

1
2
7
4
8
12
[1 2]
[2 6]
[5 6 7 8]
[False False False False]
[1 3 2]
[1 2 2]


## 6. Array Operations
- [ ] Addition
- [ ] Subtraction
- [ ] Multiplication
- [ ] Division
- [ ] Power operations
- [ ] Modulus

In [7]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 + arr2)
print(arr1 - arr2)
d=np.dot(arr1, arr2)
print(d)
print(arr1/arr2)
print(arr1**2)
print(arr1%2)

[5 7 9]
[-3 -3 -3]
32
[0.25 0.4  0.5 ]
[1 4 9]
[1 0 1]
