In [1]:
import numpy as np

## 2. Creating Arrays
- [x] np.array()
- [x] 1D Arrays
- [x] 2D Arrays
- [x] 3D Arrays
- [x] Array dimensions (ndim)
- [x] Array shape
- [x] Array datatype (dtype)

In [2]:
a = np.array([1,2,3,4])
b = np.array([
    [1,2,3,4],
    [5,6,7,8]
    ])
c = np.array([[
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
    ]])
print(a.ndim)
print(b.ndim)
print(c.ndim)

print(a.shape)
print(b.shape)
print(c.shape)

print(a.size)
print(b.size)
print(c.size)

print(a.dtype)
print(b.dtype)
print(c.dtype)

1
2
3
(4,)
(2, 4)
(1, 3, 4)
4
8
12
int64
int64
int64


## 3. Special Arrays
- [x] np.zeros()
- [x] np.ones()
- [x] np.empty()
- [x] np.full()
- [x] np.eye()
- [x] np.arange()
- [x] np.linspace()
- [x] Random arrays

In [3]:
print(np.zeros((2,3)))
print(np.ones((2,3)))
print(np.full((2,3), 5))
print(np.eye(3))
print(np.empty((2,3)))
print(np.arange(0,10,2))
print(np.linspace(0,1,5))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[2.5e-323 2.5e-323 2.5e-323]
 [2.5e-323 2.5e-323 2.5e-323]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


## 5. Indexing & Slicing
- [ ] Accessing elements
- [ ] Negative indexing
- [ ] Slicing arrays
- [ ] Multi-dimensional indexing
- [ ] Boolean indexing
- [ ] Fancy indexing

In [4]:
print(a[0])
print(b[0,1])
print(c[0,1,2])

print(a[-1])
print(b[-1,-1])
print(c[-1,-1,-1])

print(a[0:2])
print(b[:,1])
print(c[0,1,:])

mask = a>5
print(mask)

print(a[[0,2,1]])
print(a[[0,1,1]])

1
2
7
4
8
12
[1 2]
[2 6]
[5 6 7 8]
[False False False False]
[1 3 2]
[1 2 2]


## 6. Array Operations
- [ ] Addition
- [ ] Subtraction
- [ ] Multiplication
- [ ] Division
- [ ] Power operations
- [ ] Modulus

In [5]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 + arr2)
print(arr1 - arr2)
d=np.dot(arr1, arr2)
print(d)
print(arr1/arr2)
print(arr1**2)
print(arr1%2)

[5 7 9]
[-3 -3 -3]
32
[0.25 0.4  0.5 ]
[1 4 9]
[1 0 1]


In [6]:
print(np.sum(arr1))
print(np.mean(arr1))
print(np.median(arr1))
print(np.std(arr1))
print(np.var(arr1))
print(np.min(arr1))
print(np.max(arr1))
print(np.argmin(arr1))
print(np.argmax(arr1))

6
2.0
2.0
0.816496580927726
0.6666666666666666
1
3
0
2


In [8]:
print(np.reshape(arr1, (3,1)))
print(c.flatten())
print(np.ravel(c))
print(arr1.T)
print(np.swapaxes(c, 0, 1))

[[1]
 [2]
 [3]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[1 2 3]
[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]


## 10. Joining Arrays
- [ ] concatenate()
- [ ] stack()
- [ ] hstack()
- [ ] vstack()

In [9]:
f=np.concatenate((arr1, arr2))
print(f)
g=np.stack((arr1, arr2), axis=0)
print(g)
h=np.stack((arr1, arr2), axis=1)
print(h)
i=np.hstack((arr1, arr2))
print(i)
j=np.vstack((arr1, arr2))
print(j)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


## 11. Splitting Arrays
- [ ] split()
- [ ] hsplit()
- [ ] vsplit()

In [18]:
h=np.split(f, 2)
print(h)
i=np.hsplit(b, 2)
print(i)
print(np.ndim(c))
j=np.vsplit(b, 2)
print(j)


[array([1, 2, 3]), array([4, 5, 6])]
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
3
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [19]:
e=np.array([9,7,5,3,1])
print(np.sort(e))
print(np.argsort(e))
print(np.where(e>5))
print(np.unique(e))

[1 3 5 7 9]
[4 3 2 1 0]
(array([0, 1]),)
[1 3 5 7 9]


In [20]:
# Original data array
temperatures = np.array([15, 32, 18, 40, 22])

# Create the boolean mask
hot_days_mask = temperatures > 30
print(hot_days_mask)
# Output: [False  True False  True False]

# Apply the mask to filter the original array
high_temps = temperatures[hot_days_mask]
print(high_temps)
# Output: [32 40]


[False  True False  True False]
[32 40]


In [21]:
ages = np.array([12, 25, 17, 45, 60, 15])

# Filter for ages between 13 and 19 (teenagers)
teenager_filter = (ages >= 13) & (ages <= 19)
teenagers = ages[teenager_filter]
print(teenagers)
# Output: [17 15]


[17 15]


In [ ]:
print(np.dot(arr1, arr2))
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
print(np.matmul(mat1, mat2))
print(np.transpose(mat1))
print(np.det(mat1))
print(np.inv(mat1))
